name: capyscript
description: >-
version: 0.1.3

environment:
  sdk: ">=3.4.0"

dependencies:
  json_annotation: ^4.9.0
  http: ^1.2.2
  args: ^2.5.0
  path: ^1.9.0
  intl: ^0.19.0
  html: ^0.15.4
  logger: ^2.4.0


dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
