name: capyscript
description: >-
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.2
  args: ^2.4.2
  path: ^1.9.0
  intl: ^0.19.0
  html: ^0.15.4

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
