const Map<String, List<String>> moduleFunctions = {
  'http': [
    'httpGet',
    'httpPost',
    'useHeaders',
    'getHeaders',
    'registerInterceptorController',
    'executeJsScript',
  ],
  'io': ['print'],
  'json': ['jsonEncode', 'jsonDecode'],
  'converter': ['parseInt', 'parseDouble', 'parseString'],
  'date': ['createDateFormatter', 'parseDate'],
  'html': ['createHTMLParser'],
  'manga_models': [
    'buildGallery',
    'buildConcrete',
    'buildChapter',
    'buildChapterGroups',
    'buildPages',
    'statusAnnounce',
    'statusCanceled',
    'statusOngoing',
    'statusPaused',
    'statusReleased',
    'statusUndefined',
  ],
  'anime_models': [
    'buildGallery',
    'buildConcrete',
    'buildAnimeVideo',
    'buildAnimeVideoGroup',
    'statusAnnounce',
    'statusCanceled',
    'statusOngoing',
    'statusPaused',
    'statusReleased',
    'statusUndefined',
    'typeIframe',
  ],
};
